apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: links-page
  namespace: links
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - anildev.io
      secretName: anildev-tls
  rules:
    - host: anildev.io
      http:
        paths:
          - path: /links
            pathType: Prefix
            backend:
              service:
                name: links-page
                port:
                  number: 80